[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200


lib_deps =
    ; --- LIBRERÍAS DE RED Y DATOS (El Cerebro) ---
    knolleary/PubSubClient @ ^2.8                ; Para enviar datos al Dashboard (MQTT)
    bblanchon/ArduinoJson @ ^6.21.3              ; Para estructurar los datos en formato JSON

    ; --- LIBRERÍAS DE HARDWARE (Los Sentidos) ---
    adafruit/DHT sensor library @ ^1.4.6         ; Para el sensor de Temperatura y Humedad
    adafruit/Adafruit Unified Sensor @ ^1.1.14   ; Dependencia obligatoria del DHT
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4     ; Para tu pantalla LCD 1602
    bogde/HX711 @ ^0.7.5                         ; Para la balanza de alimento de 5KG
    madhephaestus/ESP32Servo @ ^3.0.5            ; Para mover los motores de las compuertas